 steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcloudcicd:$COMMIT_SHA', '.']
 - name: 'ruby:2.6.1-alpine3.9'
   args: ['echo', '"rspec"','testify']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/gcloudcicd:$COMMIT_SHA']
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'gcloudcicd'
   - '--image'
   - 'gcr.io/$PROJECT_ID/gcloudcicd:$COMMIT_SHA'
   - '--region'
   - 'europe-west1'
   - '--platform'
   - 'managed'
 images:
 - 'gcr.io/$PROJECT_ID/gcloudcicd:$COMMIT_SHA'